apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hipstershop
  namespace: hipstershop-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/jorgevizu4/prueba-argocd
      path: charts/hipstershop/helm
      targetRevision: main
      helm:
        valueFiles:
          - $values/resources/apps/hipstershop/values.yaml
    - repoURL: https://github.com/jorgevizu4/prueba-argocd
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: hipstershop-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3