apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth-secret
    namespace: keycloak
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:JALuMAEuaRkq2sLa,iv:Sd8s0f+0+2Fjmp8x/Jv7q/bW9EFibWho4Y0aFTr/nhE=,tag:lvdhGsQiERdy3TymWWsH7A==,type:str]
sops:
    lastmodified: "2026-03-23T15:04:10Z"
    mac: ENC[AES256_GCM,data:7sCBKhgy9qjBpQaSp3P4xnyk/qp7KX2qXiDdzFh/NRmFGotlTw69v4SEh56qYaCSJRXX4ISWyRh3o+nHlRMYTed0SHwuCAB/GcAvPScPDT0j8gKGW12Uc2qHjbaz7NaxoZhl5X2mUBkbA0BncGXXevF+yQ8MnrIaflFOJKx/P3o=,iv:MxdUYEApkwVG9z47nwJUikqkVfk9LViqd5omu6pC/pQ=,tag:fFxAiTRg+5sC6qndadhJsQ==,type:str]
    pgp:
        - created_at: "2026-03-23T15:04:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+HzkLdZPYJSAQ/8CZ5k9kTlhW2ROEQyHWhUSelUZ1TuImZd8csQ+T/2ng9p
            s9pyN6zCsZqY3iM4MyU71wvL1RQ0quVvbiGIEWJ42tU30gaS4FFK70M+65u5l0Hg
            fU2EuKKtev54eXMZH7NVISGOSC7/jAGNTkBCluYiGeC41NRZ2bAJDtIedEmCcQcQ
            YNlS07A0okbTf8lo5uaTZ8/5YLgjQexFYQNDpxqkILlipHTc/iQNsEGWQfaasENn
            P3FTuNLFIuqpmjq2sK5nDmxI0V6gGGOm6mYXyv0M+xvH8K28jjKBN03zVqNfseGh
            ex7mB22pmqoLEEgqW06kXt02DyEz5qNpdix6OytYnlyWaTqMBUNG0SjRGi4ikXPp
            go487/g8X3UOb52yKucuBqzCVHXbUOMV1+Xohr3tn9HGZ8shw3Ch5V422c/PxYYs
            bpkO6DTYJriVtPMBvIBmiAe/n64JPd/k2FnBgpNolLDZ8dtjbBd8Um9F+NkOkNma
            Jf3mtkTcKGu/Z+ZqXLgOQcQgDAwB35/KWC3jV3C9DYEN3uvqSvpTq001yTKOc+yg
            pfnFpwfcuBGoINdoIZ6qOYsqytIqVgHrfBuUi56rU7wZRkTbuDx2FGS3A7iWYXuN
            x7iTqbywP14OUjLo7ICm6cIJZV7CLcRBI3WlKf0Y34I35dSGXsbOe+yIkWR5/ojU
            aAEJAhB7vx7f6TeqPhqksaixFV3Sco6r0bzzsslgnzjGRk/HrB2EOLbb+Ho4e/8P
            t8jwHWLtrS7yN2mD+mxJSpms1zxyEX7MckYV9Qm3b3dryR2QA79ILKW+ANw7HDVd
            A25gaH8WYNqK
            =rwyY
            -----END PGP MESSAGE-----
          fp: ADEFA215B71C8D871E5D26842208D1DBCE11B9B2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-secret
    namespace: keycloak
type: Opaque
stringData:
    POSTGRES_USER_PASSWORD: ENC[AES256_GCM,data:oJ78EpwSmHb0Bv68,iv:Ehrur/nkGcSOGin0bvTsFfxZ7cXvTznP5DM5+9s085Q=,tag:ZQ4ZS7Otg/q2STRGk2VyKw==,type:str]
    POSTGRES_ADMIN_PASSWORD: ENC[AES256_GCM,data:mvWE4SZYWEfYCIWi,iv:7Y8bi1sAg9WjlgOlGs5Y5bmJIChrerlhCu+4AdjXpqE=,tag:eElAlmZaBe3E2P+b7YTMPw==,type:str]
sops:
    lastmodified: "2026-03-23T15:04:10Z"
    mac: ENC[AES256_GCM,data:7sCBKhgy9qjBpQaSp3P4xnyk/qp7KX2qXiDdzFh/NRmFGotlTw69v4SEh56qYaCSJRXX4ISWyRh3o+nHlRMYTed0SHwuCAB/GcAvPScPDT0j8gKGW12Uc2qHjbaz7NaxoZhl5X2mUBkbA0BncGXXevF+yQ8MnrIaflFOJKx/P3o=,iv:MxdUYEApkwVG9z47nwJUikqkVfk9LViqd5omu6pC/pQ=,tag:fFxAiTRg+5sC6qndadhJsQ==,type:str]
    pgp:
        - created_at: "2026-03-23T15:04:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+HzkLdZPYJSAQ/8CZ5k9kTlhW2ROEQyHWhUSelUZ1TuImZd8csQ+T/2ng9p
            s9pyN6zCsZqY3iM4MyU71wvL1RQ0quVvbiGIEWJ42tU30gaS4FFK70M+65u5l0Hg
            fU2EuKKtev54eXMZH7NVISGOSC7/jAGNTkBCluYiGeC41NRZ2bAJDtIedEmCcQcQ
            YNlS07A0okbTf8lo5uaTZ8/5YLgjQexFYQNDpxqkILlipHTc/iQNsEGWQfaasENn
            P3FTuNLFIuqpmjq2sK5nDmxI0V6gGGOm6mYXyv0M+xvH8K28jjKBN03zVqNfseGh
            ex7mB22pmqoLEEgqW06kXt02DyEz5qNpdix6OytYnlyWaTqMBUNG0SjRGi4ikXPp
            go487/g8X3UOb52yKucuBqzCVHXbUOMV1+Xohr3tn9HGZ8shw3Ch5V422c/PxYYs
            bpkO6DTYJriVtPMBvIBmiAe/n64JPd/k2FnBgpNolLDZ8dtjbBd8Um9F+NkOkNma
            Jf3mtkTcKGu/Z+ZqXLgOQcQgDAwB35/KWC3jV3C9DYEN3uvqSvpTq001yTKOc+yg
            pfnFpwfcuBGoINdoIZ6qOYsqytIqVgHrfBuUi56rU7wZRkTbuDx2FGS3A7iWYXuN
            x7iTqbywP14OUjLo7ICm6cIJZV7CLcRBI3WlKf0Y34I35dSGXsbOe+yIkWR5/ojU
            aAEJAhB7vx7f6TeqPhqksaixFV3Sco6r0bzzsslgnzjGRk/HrB2EOLbb+Ho4e/8P
            t8jwHWLtrS7yN2mD+mxJSpms1zxyEX7MckYV9Qm3b3dryR2QA79ILKW+ANw7HDVd
            A25gaH8WYNqK
            =rwyY
            -----END PGP MESSAGE-----
          fp: ADEFA215B71C8D871E5D26842208D1DBCE11B9B2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
