apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth-secret
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:HDZIF3dx3uqrR1sg,iv:NiX0bCB3niSb1864Qz659bjcho4bdZ+fz4q2qo5EsAY=,tag:jCPJxkSSgwu64ydizBefIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y9rrfg6jq0qwveuja6xl2jcv5yuf5lytra87r5pdvu5x4a25s4wskd6l4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWHZSdXJUTnFicTEwWXZQ
            MWg1N1NCclgrRjhVWk1zczhTcCswQnJzckQ0CnRkYmY5ZVlXVEoxWTMxTXlpNTI1
            cXpad0E5a0dRaExrU2J4Q0VtdUNYaGcKLS0tIFFSL2t1c0JZMkk3dWl0NVJaS2Nw
            eEJTOTd2bnN5c3RpU1FpMlU1WCtVOE0KPEz5eunLvwpKUnyUvFi/BpdmqP0wLpAq
            AbOfGlI+QRSNu/c/OuxuU8GiMa8RpSBScQZ8frY7Q4LtUAMX8sa2fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T14:29:44Z"
    mac: ENC[AES256_GCM,data:imnrV1ltS87eDSlsHUywGz0VNwvjyevNanm49s2+oXLWeXxNGQvjxLFS5/tQzhbgjpSu7AEIrc7gFFv6tdwmSU9nJKejnCV6q7MKufzoAJ94/FUAolvBTru4vNEt442B5rGk5Q3bNyXKPE97fU/rrE7GHByxFXZfsW6cEE7oLCk=,iv:pKp61GfYynvBrXq9Fz2wDi3NWy/x+h5loD51eR6hSFc=,tag:ESCFgMVxWnAX/uBYX/DMFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-secret
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:zACReuBMRT/EvaFW,iv:V14+8HN09KLqgmkeBzllOXo2K1B+qFOBReki4VhM7z4=,tag:qxMcpk1k29D0RvBedG91Zw==,type:str]
    postgres-password: ENC[AES256_GCM,data:yQBFeA+9sxvK/LwV,iv:OsocUTpvBWvXmXJsbTNq0KdQYK05mLXgBsBLPS+6tg4=,tag:IgL0UwqVSTu3mx3UK0VZ6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y9rrfg6jq0qwveuja6xl2jcv5yuf5lytra87r5pdvu5x4a25s4wskd6l4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWHZSdXJUTnFicTEwWXZQ
            MWg1N1NCclgrRjhVWk1zczhTcCswQnJzckQ0CnRkYmY5ZVlXVEoxWTMxTXlpNTI1
            cXpad0E5a0dRaExrU2J4Q0VtdUNYaGcKLS0tIFFSL2t1c0JZMkk3dWl0NVJaS2Nw
            eEJTOTd2bnN5c3RpU1FpMlU1WCtVOE0KPEz5eunLvwpKUnyUvFi/BpdmqP0wLpAq
            AbOfGlI+QRSNu/c/OuxuU8GiMa8RpSBScQZ8frY7Q4LtUAMX8sa2fA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T14:29:44Z"
    mac: ENC[AES256_GCM,data:imnrV1ltS87eDSlsHUywGz0VNwvjyevNanm49s2+oXLWeXxNGQvjxLFS5/tQzhbgjpSu7AEIrc7gFFv6tdwmSU9nJKejnCV6q7MKufzoAJ94/FUAolvBTru4vNEt442B5rGk5Q3bNyXKPE97fU/rrE7GHByxFXZfsW6cEE7oLCk=,iv:pKp61GfYynvBrXq9Fz2wDi3NWy/x+h5loD51eR6hSFc=,tag:ESCFgMVxWnAX/uBYX/DMFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
