image:
  repository: bitnamilegacy/keycloak
  tag: 26.3.2-debian-12-r1

auth:
  adminUser: admin
  adminPassword: jorgevizuete

postgresql:
  enabled: true
  auth:
    username: jorge
    password: jorgevizuete
    database: keycloakdb
  fullnameOverride: postgresql
  image:
    repository: bitnamilegacy/postgresql
    tag: 16-debian-12
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
      tag: 12-debian-12-r50
  metrics:
    image:
      repository: bitnamilegacy/postgres-exporter
      tag: 0.17.1-debian-12-r15

extraEnvVars:
- name: KEYCLOAK_DATABASE_HOST
  value: postgresql
- name: KEYCLOAK_DATABASE_PORT
  value: "5432"
- name: KEYCLOAK_DATABASE_USER
  value: jorge
- name: KEYCLOAK_DATABASE_PASSWORD
  value: jorgevizuete
- name: KEYCLOAK_DATABASE_NAME
  value: keycloakdb

keycloakConfigCli:
  enabled: true
  backoffLimit: 3
  image:
    repository: bitnamilegacy/keycloak-config-cli
    tag: 6.4.0-debian-12-r11
  configuration:
    demo-realm.yaml: |
      realm: demo
      enabled: true
      displayName: Demo Realm
      registrationAllowed: false
      resetPasswordAllowed: true

      roles:
        realm:
          - name: app-user
          - name: app-admin

      clients:
        - clientId: frontend-app
          name: Frontend App
          enabled: true
          protocol: openid-connect
          publicClient: true
          directAccessGrantsEnabled: true
          standardFlowEnabled: true
          redirectUris:
            - "http://localhost:3000/*"
          webOrigins:
            - "+"
          defaultClientScopes:
            - profile
            - email
            - roles
          optionalClientScopes:
            - offline_access
          roles:
          - name: read
          - name: write
          - name: admin
