# Default values for shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: v2
name: hipstershop
version: 0.1.0

dependencies:
- name: adservice
  version: 0.1.0
  repository: "file://charts/adservice"

- name: cartservice
  version: 0.1.0
  repository: "file://charts/cartservice"

- name: checkoutservice
  version: 0.1.0
  repository: "file://charts/checkoutservice" 

- name: currencyservice
  version: 0.1.0
  repository: "file://charts/currencyservice"

- name: emailservice 
  version: 0.1.0
  repository: "file://charts/emailservice"  
  
- name: frontend
  version: 0.1.0
  repository: "file://charts/frontend"
  
- name: paymentservice
  version: 0.1.0
  repository: "file://charts/paymentservice"  
  
- name: productcatalogservice
  version: 0.1.0
  repository: "file://charts/productcatalogservice"

- name: recommendationservice
  version: 0.1.0
  repository: "file://charts/recommendationservice"

- name: shippingservice
  version: 0.1.0
  repository: "file://charts/shippingservice"