# Default values for shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiVersion: v2
name: hipstershop
version: 0.1.0

app:
  name: hipstershop
  namespace: hipstershop-demo