---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-auth-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgB8xPmoTIwnKdoIo0h+D8oLyq3V6zAsGvtgfo+1asFbneIcKGtebiScEbh5uCMKOWphTyYMAchXFYYSPJYLq2iYKh4iNBusrwJsXE/gsyl2nMiR5NLz1JAqszZjJKE9z7Ib9QJKRxepcuSrnbIG+aLDZvHMYLJrKyhDDQUDo+5CBDYoK6H+m8uFXhiNAWBPw2wfcBKsyFduee0CUCi3xJDbjcvirqO8XrxvwX5IHH4aFHUz88NhR7INLY76AvAd5bdar5uS0+I+1EOofsi7ckR/JyZXWlFJvFkwB8cmi2im0Gtwb5ORqxymABx/i8wi69hQlbGN216pcTtECarkAa01KNi+42BS1kv/uEbYaYOunUkLa3eCb+UPxZogfdwstSlVetXHj6IxZM/IcTDYSLiINHwsr7r2th4txxu5R+tUxZu7OuH6URsAwH5p41Mib+i3Zov28EU/lZZcSdl74qlnw/HuKRZgUSl+fx/d5UQapT4uK2ORk1Jlm/FnwVi5o1Gle34lFSE77FUoF3S8jKa3iNYGZ36KBtb/1WGd5Apxig7ODz03UdPQFQobhscq6iNIdtlsfvVDaWwK8GMop31fLMQJlmvJgLIW57IwjENdiknRV0BaclHHTdG67cMCLQ3YwVYg2c0FQMhuN2m15Y9JgNWKiQt9+6tDlx7toIveeOugPq5bxUjn0TJfqgICTxep1UUL4VBQD7sMY+M=
  template:
    metadata:
      name: keycloak-auth-secret
      namespace: keycloak
    type: Opaque
