apiVersion: v1
kind: Secret
metadata:
    name: keycloak-auth-secret
    namespace: keycloak
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:D8CZbLkpvpNou+y3,iv:bZdL4/u2LrAYvVo1yxpkBYnX/Drk+c3w+17PzoL2FXU=,tag:RweqWD2fZvoKf8nDVGOTlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y9rrfg6jq0qwveuja6xl2jcv5yuf5lytra87r5pdvu5x4a25s4wskd6l4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a21xY1lRTjNUNFU3K25C
            b3hpYTRTWVpvRWNkRmFvYzhZS01HMWxzRlFZCjg3M09aODVrbXdNT3R4KzJvWFZ5
            UmZxd1RUNjFvMUZyQkUwWHlLZUhVK0kKLS0tIE1jc2JnbThIL0s0Sk4wb1FOVXo0
            M1Z1MmpKbHhsMVRCcnhKMW4wYktzaTQKknQ4sBecENMbqbSbzenn8vRgIq+LB4r+
            YFd7g/J1KBRz8b7bSVs8rvn1W4vlMVt2d2MgYeRzbG9bTEPHhgSzzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T10:41:30Z"
    mac: ENC[AES256_GCM,data:CngetW40KKPHBIe3Vnp2Tj8vuyxrfMT/WB2Ir7KQLO0D8ArhpKvpQ+ledlW78bCxD47A08wb+j+Mh+UGbuSddmXjnsflbb8f1jXIYYX4vdaJ3o/RGGzdyHyBs5de78+JAe1CVVSmF+TVE+pvt9IHPU5EZYr20PyLe1j9S/rd6XY=,iv:12waAYZUcL6IgBzPreavDVQl9vhzuQDEgh5xB89fOkc=,tag:KShwZW6wIo8IzBqVozUj+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
