apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-secret
    namespace: keycloak
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:qaLmNhz8Yy2Kah8W,iv:+8syr3XVcfO2CMCUHOIXjxB7IiGpa9Jw8BBYY61CXmY=,tag:2WBKcPE7Y7PIu1VAg0L6CA==,type:str]
    postgres-password: ENC[AES256_GCM,data:Cp2+LGuUZv12b14Q,iv:BFg1R2VAJ8vcq8cg3Jxn5VcewrZ7Wrg4/VFS341nc1A=,tag:COMJn1n+F9NsNoJvMkXKmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y9rrfg6jq0qwveuja6xl2jcv5yuf5lytra87r5pdvu5x4a25s4wskd6l4h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXalhjd1M2MSt4cDhvNVVs
            RHozWW90aWZjTENNNmFFMlRFKzBVNlBJWWlvCi80UW4xbTBuWTdCczNYU0NxUHla
            cU55am1hNEN3YThzeVFKVW1zdlhlRzgKLS0tIENRL2k1Q3BlQU8rZURrYlRMUkw2
            WHk3SWRrYTVwR0VhWGs1RkFOd05UTGcKDAlb5ehhWM7+Jgx/crMCG2DtPWnclchG
            RNSTDipcA584qE//pSdIzpQ8KDDWFMo0ot22A+Q63NyvFmejmrAbGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T10:41:30Z"
    mac: ENC[AES256_GCM,data:wJgi1P2nSJj1ES7jIvfivIZgUmQa0qhbNWsGyHjm+fnFu5BCpjoi8dEf6WExYlz0kwDkeIIxwA1CIHHMJxpSruO54vvZ7CrfQaSMSqItdLkol8vMIx2HGrih9BtHxX/F74K6TMUbPeppiG6UnoPy3+WUKIMc2coQ93I0dKKH0R4=,iv:znuOFm6qyyWABRRDYbfUIJC7dVZVhVyep/NU1NNrEuA=,tag:AydvTeHgQRdL7+nWaJ251Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
