---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-postgresql-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgC6GtSsawcHy0W/oEW9dc3AyWtaD8tmxRzY6AlfKz872/Bu5X3WdrIFfxsQwTyKYwMV7NamqAqzYE8d1+vPazjVvOtSzngO1cFMpMPJCaoMB0FWx2OpnVU0DS6qPn6oT9Gd6ZfMwUVl8Bz6OhzhNIkTQgfaMs445IMaxBbbJDJJUvGY3KArMEeimDAC/HD70ZbHQSHrj63k/Q9Vf2ewAKBa2LFDdbNspXZz3fBwKCD7ujOTMohkoWoKD7VtHTtAKaUtYuYkpXRPSVdRS11b0fQTB2XV40A5kiUIHzHBxIRLJ4+dLhay44tGDE84Put0ZaMVs1eEeIhorAG4D4O/8bMSn5WdtaaKJqEiXe8E5KlI4NFZqxY42mm/sJdkoO5qtDcCEG69MxfQZ333aIx7T8a8VbsbUFdEjl5xS2ZuGBR/Oyb6Lj/aFyGoyYgf9PUUOXp+1chy7wWZS1F3xYQ5qtwR1YN6RmmHf86NN9E8gWJ8k7bELPr1CUlXByuEg2VUP5TTWtLgh87FqSCc3P9AJOwzDML5Csnnuu+p1ajGPCQTR2W13H9+vtUp4GIBcrqbJ42PtalASeMJ4/co7mP4sGAdcVLYRxiWCyP/crc89W8xgSTf7wVkg5TScmu0OJCaKdTkkbpuDtlCOpKfSiAw7t6Yse8/cJDZy5HR7AzPXFrwj0xf0Q1UMR355DOfeLP2UJzCeTFKpHv8byqBgLI=
    postgres-password: AgBSK9HqTozqRtRMHMie4PgGVftAC6QencApf43iQZJYBDnw5kBcOgdEQFV9SSWQJpiNcIa4zB+QykuAQcWKLxmaj02RLGL5N4Rqe3ovbnf8vJ3NP1cXD2A6/MDDiASZZhXyF4maVlHGh69dN6qPemTDNV9FjpUlpFicHfuig8AX6naibHh578+MkTowqW1pSwYPK6XX14xWTg6eU0Q4clDUbZYUUe8/4ZPR1PgHVZ8CqHxv4+/xNdHQcA0K79VY0QnWb/RG13fonThOQxdLBSe9Q+1UbaG1xd+FZFuXlfb/L+xbJCX0SOraqe8EIsnntoNxzHM0D0FNE2uEbttHy4HO45wzbprovU9Wi9n48lUgQ8QeBZIwhTmUUOZCEsTC8hyZsLPU0kGR5hNGLfk8DZP9EQ29+rD+NyWOqQNVSrXIrEMRccowiwl3xLQ6HUg0JhBG4KsnPr0o8JxgfxuKVdifCDkowsv9040wkrnOGq+gycdSyP4ANA2w/huf960WS4cyo3XoZzdSWeFvQaWY/gXi1OD4kv+nnvF0LjBV3pnlMkkMZbW2zVg1KEhSpip8x47ikrlThx9oExJ3jgNqJu6t+V318lTlvrFhIIqNrcVbPgCdYDImsblvNWIHLMibXW0caGHmdti/mXdY1FB3M8+xCUzh6P5cj/+md/e+jTS533saRegrKZ7GaKojUXK21AEtT/i+kQ6BYKLLbtk=
  template:
    metadata:
      name: keycloak-postgresql-secret
      namespace: keycloak
    type: Opaque
