apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prueba-argocd-app
  namespace: demo-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/jorgevizu4/prueba-argocd.git'
    path: manifests/apps/__overlays
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true