apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ejemplo-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/jorgevizu4/prueba-argocd
      path: charts/ejemplo-app
      targetRevision: main
      helm:
        valueFiles:
          - $values/resources/apps/ejemplo-app/values.yaml
    - repoURL: https://github.com/jorgevizu4/prueba-argocd
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ejemplo-app-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3